# Generated by Django 5.1.5 on 2025-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Processamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_identificador", models.CharField(max_length=10)),
                ("caller", models.CharField(max_length=30)),
                ("porcentagem", models.CharField(max_length=10)),
                ("mensagem1", models.CharField(max_length=150)),
                ("mensagem2", models.CharField(max_length=150)),
                ("finalizado", models.BooleanField()),
            ],
        ),
    ]
