# Generated by Django 5.1.5 on 2025-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processamento",
            name="finalizado",
            field=models.BooleanField(default=False),
        ),
    ]
